### ISSUE TITLE
Error when picking a colour

### ISSUE THREAD

**Issue by unclear125** [TomDotBat/pixel-karts#6]
**Describe the bug**
Whenever i go to change the colour of the gokart it make an error and will not change the colour.
Same for the underglow  

The error: 

Underglow 

[pixel-karts] addons/pixel-karts/lua/pixelkarts/garage/vgui/cl_underglow.lua:48: attempt to call field 'RGBToHex' (a nil value)
  1. OnChange - addons/pixel-karts/lua/pixelkarts/garage/vgui/cl_underglow.lua:48
   2. SetColor - addons/pixel-ui-1.2.3/lua/pixelui/elements/cl_color_picker.lua:65
    3. unknown - addons/pixel-karts/lua/pixelkarts/garage/vgui/cl_underglow.lua:128

Timer Failed! [Simple][@addons/pixel-karts/lua/pixelkarts/garage/vgui/cl_underglow.lua (line 127)]

Body colour 

[pixel-karts] addons/pixel-karts/lua/pixelkarts/garage/vgui/cl_color.lua:37: attempt to call field 'RGBToHex' (a nil value)
  1. OnChange - addons/pixel-karts/lua/pixelkarts/garage/vgui/cl_color.lua:37
   2. SetColor - addons/pixel-ui-1.2.3/lua/pixelui/elements/cl_color_picker.lua:65
    3. unknown - addons/pixel-karts/lua/pixelkarts/garage/vgui/cl_color.lua:124

Timer Failed! [Simple][@addons/pixel-karts/lua/pixelkarts/garage/vgui/cl_color.lua (line 123)]

**Comment by TomDotBat** [comment]
I don't believe you're using the latest version of PIXEL Karts and PIXEL UI. Please update it and let me know if that fixes your issue.

**Comment by TomDotBat** [comment]
https://github.com/TomDotBat/pixel-karts/blob/420916a51da9d2fd2cdabc23fb71f6c08f371b02/lua/pixelkarts/garage/vgui/cl_underglow.lua#L48

The line mentioned in the error doesn't call the method `RGBToHex()`, you are not using the latest version.

**Comment by unclear125** [comment]
So should i just redownload it off the GitHub again?

**Comment by TomDotBat** [comment]
Yes redownload this and [PIXEL UI](https://github.com/TomDotBat/pixel-ui).
